"use client";

import { Gavel, LoaderCircle, RefreshCw, Waypoints } from "lucide-react";

import type { TransactionSnapshot } from "@/lib/covenant/types";

import { StatusBadge } from "./StatusBadge";

function executionLabel(snapshot: TransactionSnapshot) { if (snapshot.executionSucceeded === true) return "execution returned"; if (snapshot.executionSucceeded === false) return "execution reverted"; return "execution pending"; }

export function TransactionRail({ transactions, busy, onAppeal, onRefresh }: { dashboard?: unknown; transactions: TransactionSnapshot[]; busy: boolean; onAppeal: (snapshot: TransactionSnapshot) => void; onRefresh: (snapshot: TransactionSnapshot) => void; }) {
  return <section className="panel overflow-hidden"><div className="border-b border-black/10 p-5"><h2 className="display-title text-2xl">This session</h2><p className="mt-2 text-xs leading-5 text-[#6b6d67]">A decision is not durable until finality. Track signed calls here.</p></div>{transactions.length ? <ul className="divide-y divide-black/10">{transactions.map((snapshot) => <li key={snapshot.hash} className="p-4"><div className="flex items-start justify-between gap-3"><p className="min-w-0 truncate text-sm font-bold">{snapshot.label}</p><StatusBadge status={snapshot.phase} title={`Consensus: ${snapshot.statusName || "unknown"}`} /></div><p className="mt-2 break-all font-mono text-[10px] text-[#777972]">{snapshot.hash}</p><p className="mt-2 text-xs leading-5 text-[#5e605b]">{snapshot.detail}</p><div className="mt-2 flex flex-wrap gap-2 text-[10px] font-bold text-[#777972]"><span>{snapshot.statusName || "status pending"}</span><span>·</span><span>{executionLabel(snapshot)}</span></div>{snapshot.triggeredIds.length ? <p className="mt-3 flex items-center gap-2 rounded-[10px] bg-[#dfe6ff] p-2 text-xs font-bold text-[#2449b8]"><Waypoints className="size-4" />{snapshot.triggeredIds.length} finality-safe child message(s)</p> : null}<div className="mt-3 flex gap-2"><button type="button" className="secondary-button !min-h-9 flex-1 !py-1 !text-xs" disabled={busy} onClick={() => onRefresh(snapshot)}>{busy ? <LoaderCircle className="size-3.5 animate-spin" /> : <RefreshCw className="size-3.5" />}Refresh</button>{snapshot.appealable ? <button type="button" className="primary-button !min-h-9 flex-1 !py-1 !text-xs" disabled={busy} onClick={() => onAppeal(snapshot)}>{busy ? <LoaderCircle className="size-3.5 animate-spin" /> : <Gavel className="size-3.5" />}Appeal</button> : null}</div></li>)}</ul> : <p className="p-5 text-sm leading-6 text-[#6b6d67]">Signed calls from this browser session will appear here with consensus, execution, and finality state.</p>}</section>;
}
